apiVersion: v1
kind: Namespace
metadata:
  name: zulip
---
# Persistent Volume for Postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: zulip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Postgres Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: zulip
            - name: POSTGRES_PASSWORD
              value: zulip-pass
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
# Memcached Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.6
          ports:
            - containerPort: 11211
---
# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: zulip
            - name: RABBITMQ_DEFAULT_PASS
              value: zulip-rabbit-pass
---
# Zulip Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zulip
  template:
    metadata:
      labels:
        app: zulip
    spec:
      containers:
        - name: zulip
          image: eligetipavankumar/zulipapp:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_HOST_PORT
              value: "5432"
            - name: DB_USER
              value: zulip
            - name: SECRETS_postgres_password
              value: zulip-pass
            - name: SETTING_MEMCACHED_LOCATION
              value: memcached:11211
            - name: SETTING_RABBITMQ_HOST
              value: rabbitmq
            - name: SECRETS_rabbitmq_password
              value: zulip-rabbit-pass
            - name: SETTING_REDIS_HOST
              value: redis
            - name: SECRETS_redis_password
              value: zulip-redis-pass
            - name: SECRETS_secret_key
              value: supersecretkey
            - name: SETTING_EXTERNAL_HOST
              value: zulip.local
            - name: SETTING_ZULIP_ADMINISTRATOR
              value: admin@example.com
---
# Zulip Service
apiVersion: v1
kind: Service
metadata:
  name: zulip
  namespace: zulip
spec:
  type: NodePort
  selector:
    app: zulip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
