apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zulip
  template:
    metadata:
      labels:
        app: zulip
    spec:
      containers:
        - name: zulip
          image: eligetipavankumar/zulipapp:latest
          ports:
            - containerPort: 9991   # Zulip default web UI port
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: zulip-service
  namespace: zulip
spec:
  type: NodePort
  selector:
    app: zulip
  ports:
    - port: 9991         # Service port
      targetPort: 9991   # Container port
      nodePort: 30091    # External access port (http://<minikube-ip>:30091)
