apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip
  namespace: zulip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zulip
  template:
    metadata:
      labels:
        app: zulip
    spec:
      containers:
        - name: zulip
          image: eligetipavankumar/zulipapp:latest
          ports:
            - containerPort: 9991   # Correct Zulip web UI port
          env:
            # Database
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "zulip"
            - name: DB_PASSWORD
              value: "zulip"
            - name: DB_NAME
              value: "zulip"

            # Redis
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

            # RabbitMQ
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "zulip"
            - name: RABBITMQ_PASSWORD
              value: "zulip"

            # Memcached
            - name: MEMCACHED_HOST
              value: "memcached"
            - name: MEMCACHED_PORT
              value: "11211"

            # Zulip specific settings
            - name: SECRETS_secret_key
              value: "dummy-secret-key"
            - name: SETTING_EXTERNAL_HOST
              value: "localhost"
            - name: SETTING_ZULIP_ADMINISTRATOR
              value: "admin@example.com"
            - name: DISABLE_HTTPS
              value: "True"
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: zulip-service
  namespace: zulip
spec:
  type: NodePort
  selector:
    app: zulip
  ports:
    - name: web
      port: 9991         # Service port
      targetPort: 9991   # Container port
      nodePort: 30091    # External access (http://<minikube-ip>:30091)
